#cloud-config
users:
  - name: student
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_key}

packages:
  - nginx

runcmd:
  - sed -i 's/listen 80 default_server;/listen 8033 default_server;/' /etc/nginx/sites-available/default
  - sed -i 's/listen \[::\]:80 default_server;/listen [::]:8033 default_server;/' /etc/nginx/sites-available/default
  - bash -c 'echo "devlab on $(hostname)" > /var/www/html/index.nginx-debian.html'
  - nginx -t
  - systemctl restart nginx
